name: PR Check and Validation

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: "True"
      ALLOWED_HOSTS: "localhost,127.0.0.1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black mypy

      - name: Run linting
        run: |
          flake8 .
          black . --check
          mypy .

      - name: Run tests
        run: |
          python manage.py test

      - name: Check migrations
        run: |
          python manage.py makemigrations --check --dry-run
          python manage.py migrate --check --dry-run
