name: PR Check and Validation

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: "True"
      ALLOWED_HOSTS: "localhost,127.0.0.1"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: make install

      - name: Validate
        run: make check
